name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: hiy7030/kkumo
          stage: main
          yaml: |
            name: kkumo
            app: java@17
            options:
              ports: "8080"
              buildenv: []
              env: 
                - name: DB_URL 
                  secret: DB_URL
                - name: DB_USERNAME 
                  secret: DB_USERNAME
                - name: DB_PASSWORD
                  secret: DB_PASSWORD
                - name: MAIL_USERNAME
                  secret: MAIL_USERNAME
                - name: MAIL_PASSWORD
                  secret: MAIL_PASSWORD
                - name: S3_API
                  secret: S3_API
                - name: S3_ACCESS_KEY
                  secret: S3_ACCESS_KEY
                - name: S3_SECRET_KEY
                  secret: S3_SECRET_KEY
                - name: S3_REGION
                  secret: S3_REGION
                - name: S3_IMAGE_URL
                  secret: S3_IMAGE_URL
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}